apiVersion: apps/v1
kind: Deployment
metadata:
  name: vue-fe
  namespace: app
  labels:
    app: vue-fe
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vue-fe
  template:
    metadata:
      labels:
        app: vue-fe
    spec:
      containers:
        - name: vue-fe
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
